spring:
  datasource:
    url: jdbc:mysql://150.158.180.158:33070
    username: root
    password: 199505
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher