server:
  port: 25968
spring:
  application:
    name: reggie-take-out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://150.158.180.158:33060/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 199505
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    port: 465
    username: 1393868638@qq.com
    password: sqyaovwbdphzhbcb
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
mybatis-plus:
  configuration:
    # address_book -> AddressBook
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
reggie:
  path: /Users/pluttooo/Desktop/ReggieFileUploadDir/
